- name: Deploy webapp
  become: true
  copy:
    src: ../webapp/go/isucondition
    dest: /home/isucon/webapp/go/
  notify: restart_webapp
- name: Deploy sql files
  become: true
  copy:
    src: "{{ item }}"
    dest: /home/isucon/webapp/sql/
  with_items:
    - ../webapp/sql/init.sh
    - ../webapp/sql/0_Schema.sql
