all:
  children:
    bench:
      hosts:
        bench01:
          ansible_host: 13.114.243.119
    nginx:
      hosts:
        nginx01:
          ansible_host: 54.199.197.192
    webapp:
      hosts:
        webapp01:
          ansible_host: 54.199.197.192
    db:
      hosts:
        db01:
          ansible_host: 54.199.197.192
    pprotein:
      hosts:
        pprotein01:
          ansible_host: 52.192.207.248
